//
//  GearOfKMUMacro.h
//  GearsOfKMU
//
//  Created by admin on 12/2/15.
//
//

#ifndef GearsOfKMU_GearOfKMUMacro_h
#define GearsOfKMU_GearOfKMUMacro_h

#define BACKGROUND_MUSIC_VOLUME 0.1f

#define STUDENTBYSEC_START 0.1f
#define MONEY_START 10
#define MONEYBYSECOND_START 2
#define KNOWLEDGE_START 0
#define STUDENT_START 10

#define MONEY_FOR_EACH_STUDENT 0.5f

#define ENGINEERING_UNLOCK true
#define MEDECINE_UNLOCK false
#define EDUCATION_UNLOCK false
#define SOCIAL_UNLOCK false
#define NATURAL_UNLOCK false
#define MUSIC_UNLOCK false

#define ENGINEERING_MONEYUNLOCK 0
#define MEDECINE_MONEYUNCLOCK 50
#define EDUCATION_MONEYUNCLOCK 100
#define SOCIAL_MONEYUNCLOCK 200
#define NATURAL_MONEYUNCLOCK 500
#define MUSIC_MONEYUNCLOCK 750

#define ENGINEERING_KNOWLEDGEUNLOCK 0
#define MEDECINE_KNOWLEDGEUNLOCK 50
#define EDUCATION_KNOWLEDGEUNLOCK 100
#define SOCIAL_KNOWLEDGEUNLOCK 200
#define NATURAL_KNOWLEDGEUNLOCK 500
#define MUSIC_KNOWLEDGEUNLOCK 750

#define ENGINEERING_MAJOR1_MAXSTUDENT 10
#define MEDECINE_MAJOR1_MAXSTUDENT 8
#define EDUCATION_MAJOR1_MAXSTUDENT 15
#define SOCIAL_MAJOR1_MAXSTUDENT 19
#define NATURAL_MAJOR1_MAXSTUDENT 30
#define MUSIC_MAJOR1_MAXSTUDENT 60

#define ENGINEERING_MAJOR1_TIMETOGRADUATE 10.0f
#define MEDECINE_MAJOR1_TIMETOGRADUATE 25.0f
#define EDUCATION_MAJOR1_TIMETOGRADUATE 13.0f
#define SOCIAL_MAJOR1_TIMETOGRADUATE 40.0f
#define NATURAL_MAJOR1_TIMETOGRADUATE 50.0f
#define MUSIC_MAJOR1_TIMETOGRADUATE 100.0f

#define ENGINEERING_MAJOR2_MAXSTUDENT 5
#define MEDECINE_MAJOR2_MAXSTUDENT 4
#define EDUCATION_MAJOR2_MAXSTUDENT 13
#define SOCIAL_MAJOR2_MAXSTUDENT 50
#define NATURAL_MAJOR2_MAXSTUDENT 25
#define MUSIC_MAJOR2_MAXSTUDENT 50

#define ENGINEERING_MAJOR2_TIMETOGRADUATE 15.0f
#define MEDECINE_MAJOR2_TIMETOGRADUATE 30
#define EDUCATION_MAJOR2_TIMETOGRADUATE 17.0f
#define SOCIAL_MAJOR2_TIMETOGRADUATE 26.0f
#define NATURAL_MAJOR2_TIMETOGRADUATE 35.0f
#define MUSIC_MAJOR2_TIMETOGRADUATE 70.0f

#endif
